{% set name = "cfgv" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8e8f552ffcc6194f4e18dd4f68d9aef0c0d58ae7e7be8c82bee3c5e9edfa513

build:
  number: 0
  script: pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - cfgv

about:
  home: https://github.com/asottile/cfgv
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Validate configuration and produce human readable error messages.
  description: Validate configuration and produce human readable error messages.

extra:
  recipe-maintainers:
    - nicoddemus
