{% set name = "cfgv" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e52591d4c5f5dead8e0f673fb16db7949d2cfb3f7da4582893288f0ded8fe560

build:
  number: 0
  skip: True  # [py<37]
  script: pip install . --no-deps --no-build-isolation --ignore-installed

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  imports:
    - cfgv
  commands:
    - pip check

about:
  home: https://github.com/asottile/cfgv
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Validate configuration and produce human readable error messages.
  description: Validate configuration and produce human readable error messages.
  dev_url: https://github.com/asottile/cfgv
  doc_url: https://github.com/asottile/cfgv

extra:
  recipe-maintainers:
    - nicoddemus
