{% set name = "cfgv" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 13d7bd4125dd3deed477cbfad9e8fb44a442f0bb627b5cd03afb6bc1899538db

build:
  number: 0
  skip: true  # [py<310]
  script: pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cfgv
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/asottile/cfgv
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Validate configuration and produce human readable error messages.
  description: Validate configuration and produce human readable error messages.
  dev_url: https://github.com/asottile/cfgv
  doc_url: https://github.com/asottile/cfgv

extra:
  recipe-maintainers:
    - nicoddemus