{% set name = "cfgv" %}
{% set version = "3.0.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "04b093b14ddf9fd4d17c53ebfd55582d27b76ed30050193c14e560770c5360eb" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - cfgv

about:
  home: https://github.com/asottile/cfgv
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Validate configuration and produce human readable error messages.
  description: 'Validate configuration and produce human readable error messages.'

extra:
  recipe-maintainers:
    - nicoddemus
