travis:
  secure:
    BINSTAR_TOKEN: hZ0ucdXLUmBXzfRoRZnRMf6vDAcCG/L/2u7ybCmcQRiIETBG0v+uKRb6QVze5TJSpyVhgVmHZz1HFVG3JyWeqAtuSga3U6JA0MUPgiwaDK+XAwoZm5+boyr2pKm9IpW1SSZMeizYm5W5stRLCWDRdT6RWKnorWVVTpOgX7jnphaFjZapzQ7wTFO7jINffRzz7YYbGUzIEFtnbKjxDj05w6bcjm6OX/xMxgBgkZ8aFc6U0Xo1CCV/S4x9Ovp2dob4wJKLn2ZWeGv6VRD3qheYiYAs2dg1yAsU6mJM73Gi2w7J9smTt7N4+2d1QclD2J7FORokwPYTkvy0TsQK/3+Ztw2hxtbIOAnYj+lgWKg1FX/tvp/1yrVj8EODBgj+beFomMAiodpg0H6QuHzTAgghkbQjte7NUWFj2l8oJ3I16WcLzJuJFUOqwl7CKqdhzOotaDVsG5smwmpmg0NQz78HI0uyn2Y/EIaSYEQZTLaPwH4ZGjiKo6xgGpg56r2UOvUUlhaVuaey0XjAEfIonMYamXjgz+RmJrXxtmvPzIiOgrZjbV9jJWrhTLckCmcb3CHZiMZVh5lwXhKjCTaHTaxNOmKdm1/vou5271PMSBc8BmCxQBo6LNNc2JeoL/Lb+REhNfODG6bXrX6zhsG+JAZeXMCre4ldb5U/bsXGrbxSF3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
