travis:
  secure:
    BINSTAR_TOKEN: da+8UHLGHi+++6z1ABRvbEGhudiuSFlSSr7QZyV2ICJsMMYV6OLRVb2bXQxDNGTUkN4yH55tFYJpDS5enaqFKwn3eVoC4pz2H1UQcBWhxxJN8VGamWVkb/In4MWVr75CT93EFQhVh7HfqrYx+OFLTOWxDJibkYyvzAFTKhDyZlhSpfFJ8LD5CpBFU2EsoiULIjSMnAijlZQIkuPYnrQGV0g1yacPVeL56ajt4Kg7vZx9RaHiwV9mGtCXmuVP3j6+TlihPvJAzbdjnJgrhkB0PTCA4cOggJ+rafywqYb1X+MYhIml2Vi4w/hLDt0hdn72cVR7YEhvNbdJZROYZwDgZL80lr0N2exoJ+zpAojXNltzeR+Vqp7B0NGZ6pv/4Lwxh+h+ar7sTFZkIwUDJUOBRNUqOlgqvga4Co8nkgIOfrm8UEWfjmz4jNrYBDQi/tnByCv9lEERfxJ6Hz324SdY/HjzdmsYK1oUmPp6djJI4fdHK/EgZWs+WU56zfRJ0KHLTxf4PKFQVS0qs1LrvO9ckPirqcuzhBJ+aojEsKsBqylDgodkh/+IFKCNkdV54jFiXKezMRWRSIWDp258OVHJFyGzvDlWkZUrzn3qo3ej2OeAvmIyPQje0cLJTYkYrzGIOGppiSPhpRJnfEoIZTmCRU1bE/WY+x2fjWEoFaE0upA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
